#!/usr/bin/env bash
#
# Require bash version >= 4.4

#include include/common.sh

if common::is_program_installed "apt-get"; then
  # Install from Ubuntu/Debian
  apt-get --yes --no-install-recommends install sysstat
elif common::is_program_installed yum; then
  # Install from RHEL/Fedora/CentOS
  yum --assumeyes install sysstat
fi

common::info "Successfully installed the sysstat package."
