#!/usr/bin/env bash
#
# Require bash version >= 4.4

#include include/common.sh
#include ceph_volume/interfaces.sh

VOLUME_IN_PARTITION=/dev/sda2
VG_NAME_PREFIX="ceph-"
LV_NAME_PREFIX="ceph-lv-"

create_lvs() {
  if [[ -b  "$VOLUME_IN_PARTITION" ]]; then
    common::info "Partition $VOLUME_IN_PARTITION already created. Destroying it..."

    local -i exit_status=0
    trace_on
    pvs --noheadings --readonly --options vg_name \
      --select "pv_name=$VOLUME_IN_PARTITION" \
    | xargs -I '{}' vgremove --force --verbose {} || exit_status=$?
    trace_off

    if (( exit_status )); then
      common::err $(( ERR_STATUS_START + 1 )) \
        "Fail to destroy the volume group for physical volume '$VOLUME_IN_PARTITION'"
    fi

    trace_on
    parted --script -- /dev/sda rm 2 || exit_status=$?
    trace_off

    if (( exit_status )); then
      common::err $(( ERR_STATUS_START + 1 )) \
        "Fail to delete partition $VOLUME_IN_PARTITION"
    fi
  fi

  if parted --script --align optimal -- /dev/sda \
    mkpart primary 33558528s 100% \
    set 2 lvm on; then

    # https://github.com/ceph/ceph/blob/v16.0.0/src/ceph-volume/ceph_volume/api/lvm.py#L771
    local -r vg_name="${VG_NAME_PREFIX}$(uuidgen)"
    trace_on
    vgcreate --force --yes "$vg_name" "$VOLUME_IN_PARTITION"
    trace_off

    # https://github.com/ceph/ceph/blob/v16.0.0/src/ceph-volume/ceph_volume/api/lvm.py#L1178
    local -r lv_name="${LV_NAME_PREFIX}$(uuidgen)"
    trace_on
    lvcreate --yes -l 100%FREE -n "$lv_name" "$vg_name"
    trace_off

    lvdisplay /dev/"$vg_name"/"$lv_name"

    common::info "Successfully created Logical Volume: $vg_name/$lv_name"
  else
    common::err $(( ERR_STATUS_START + 2 )) \
      "Fail to create a primary partition."
  fi
}

query_lvs() {
  local vg_name
  trace_on
  # triming string with xargs
  #   https://stackoverflow.com/a/12973694
  vg_name="$(
    pvs \
      --noheadings \
      --readonly \
      --select "pv_name=$VOLUME_IN_PARTITION" \
      --options vg_name | xargs
  )"
  trace_off

  if [[ -z "$vg_name" ]]; then
    common::err $(( ERR_STATUS_START + 1 )) \
      "Unable to find the volume group" \
      "associating with physical volume '$VOLUME_IN_PARTITION'"
  fi

  if ! [[ "$vg_name" =~ ^$VG_NAME_PREFIX ]]; then
    common::err $(( ERR_STATUS_START + 1 )) \
      "Unexpected volume group name: $vg_name"
  fi

  local lv_name
  trace_on
  lv_name="$(
    lvs \
      --noheadings \
      --readonly \
      --select "vg_name=$vg_name" \
      --options lv_name | xargs
  )"
  trace_off

  if [[ -z "$lv_name" ]]; then
    common::err $(( ERR_STATUS_START + 1 )) \
      "Unable to find the logical volume" \
      "under volume group '$vg_name'"
  fi

  if ! [[ "$lv_name" =~ ^$LV_NAME_PREFIX ]]; then
    common::err $(( ERR_STATUS_START + 1 )) \
      "Unexpected logical volume name: $lv_name"
  fi

  common::remote_out "$vg_name/$lv_name"
}

ceph_volume::main
