#!/usr/bin/env bash
#
# Require bash version >= 4.4
#
# This script depends on passwordless ssh and passwordless sudo via the current
# user ($USER) on remote hosts.

set -euo pipefail

readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# shellcheck source=./common.sh
. "$SCRIPT_DIR/common.sh"


usage() {
  cat <<EOF
Usage: $0 -m MON_IP -h OSD_HOST [-h OSD_HOST]... -s SCRIPT_FILE

Options:
  -m :         IP address for the cluster’s monitor daemon.
  -h :         OSD host (e.g., -h host1 -h host2).
  -s :         the remote script (relative path to the remote_script/ceph_volume dir)
               for creating and querying ceph volumes on each host.

Defining the LVS_PROVISION=no can skip the logical volumes provisioning on hosts.

All SSH connections to host clusters will use the user defined by '\$USER' (current: $USER).

EOF
}

if (( $# < 2 )); then
  usage
  exit
fi


OSD_HOSTS=()
while getopts ":m:h:s:" option; do
  case $option in
    m  ) readonly MON_IP=$OPTARG ;;
    h  ) OSD_HOSTS+=("$OPTARG") ;;
    s  ) SCRIPT_FILE=$OPTARG ;;
    \? )
      usage
      common::err $(( ERR_STATUS_START + 1 )) "Invalid option: -$OPTARG"
      ;;
    :  )
      usage
      common::err $(( ERR_STATUS_START + 1 )) "Option -$OPTARG requires an argument."
      ;;
    *  )
      usage
      exit
  esac
done
shift "$(( OPTIND - 1 ))"

if [[ -z "${MON_IP:-}" ]]; then
  usage
  common::err $(( ERR_STATUS_START + 2 )) \
    "Please specify the IP address of the monitor using '-m'"
fi

if ! [[ "$MON_IP" =~ ^[[:digit:].]+$ ]]; then
  common::err $(( ERR_STATUS_START + 3 )) "Invalid IP address: $MON_IP"
fi

if (( "${#OSD_HOSTS[@]}" == 0 )); then
  usage
  common::err $(( ERR_STATUS_START + 2 )) "Please specify OSD_HOSTS using '-h'"
fi

if [[ -z "${SCRIPT_FILE:-}" ]]; then
  common::err $(( ERR_STATUS_START + 2 )) \
    "Please specify the SCRIPT_FILE using '-s'"
fi

if ! [[ -f "$SCRIPT_DIR/remote_script/ceph_volume/$SCRIPT_FILE" ]]; then
  common::err $(( ERR_STATUS_START + 3 )) \
    "Cannot find the script file '$SCRIPT_FILE' under the remote_script/ceph_volume dir"
fi

common::debug OSD_HOSTS: "$(common::print_array OSD_HOSTS)"


install_docker_sar() {
  local -ar all_hosts=( "$MON_IP" "${OSD_HOSTS[@]}" )
  local -a param_install_docker_hosts=() param_install_sar_hosts=()
  local host

  for host in "${all_hosts[@]}"; do
    if ! ssh "${SSH_COMM_OPTIONS[@]}" "$USER@$host" \
      command -v "docker" >/dev/null 2>&1; then
      param_install_docker_hosts+=( --host "$host" )
    fi

    if ! ssh "${SSH_COMM_OPTIONS[@]}" "$USER@$host" \
      command -v "sar" >/dev/null 2>&1; then
      param_install_sar_hosts+=( --host "$host" )
    fi
  done

  if (( ${#param_install_docker_hosts[@]} )); then
    "$SCRIPT_DIR"/parallel-docker-install \
      --env INFO_LEVEL=1 \
      "${param_install_docker_hosts[@]}"
  fi

  if (( ${#param_install_sar_hosts[@]} )); then
    CMD_MODE=false "$SCRIPT_DIR"/parallel-exec-script \
      --script=install/sysstat \
      --env INFO_LEVEL=1 \
      "${param_install_sar_hosts[@]}"
  fi
}
common::stage "Check and install docker and sar..."
install_docker_sar

# shellcheck source=./remote_script/ceph_volume/interfaces.sh
. "$SCRIPT_DIR"/remote_script/ceph_volume/interfaces.sh

create_ceph_lvs() {
  local -a param_hosts
  local host

  for host in "${OSD_HOSTS[@]}"; do
    param_hosts+=( --host "$host" )
  done

  "$SCRIPT_DIR"/parallel-exec-script \
    --script ceph_volume/"$SCRIPT_FILE" \
    --env INFO_LEVEL=1 \
    --env CEPH_VOLUME_OPERATION="$CEPH_VOLUME_OPERATION_CREATE" \
    "${param_hosts[@]}"
}
if [[ "${LVS_PROVISION:-yes}" != "no" ]]; then
  common::stage "Create logical volumes on OSD hosts..."
  create_ceph_lvs
fi


deploy_ceph() {
  local -a param_host_osds
  local host host_lvs joined

  for host in "${OSD_HOSTS[@]}"; do
    host_lvs=("$(
      "$SCRIPT_DIR"/parallel-exec-script \
        --script ceph_volume/"$SCRIPT_FILE" \
        --env INFO_LEVEL=1 \
        --env CEPH_VOLUME_OPERATION="$CEPH_VOLUME_OPERATION_QUERY" \
        --host "$host" | common::parse_remote_out
    )")

    printf -v joined '%s,' "${host_lvs[@]}"
    param_host_osds+=( -o "$host:${joined%,}" )
  done

  CEPH_CLUSTER_FSID="$(
    "$SCRIPT_DIR"/ceph-deploy -m "$MON_IP" "${param_host_osds[@]}" \
      2>&1 | tee /dev/tty \
      | grep --only-matching --perl-regexp "Cluster fsid: \K[[:alnum:]-]+"
  )"
}

tear_down_ceph() {
  if [[ -z "${CEPH_CLUSTER_FSID:-}" ]]; then
    common::err $(( ERR_STATUS_START + 4 )) \
      "Unable to read the cluster fsid."
  fi

  local -a param_hosts=( --host "$MON_IP" )
  local host

  for host in "${OSD_HOSTS[@]}"; do
    param_hosts+=( --host "$host" )
  done

  INFO_LEVEL=1
  common::info "Tearing down the Ceph Cluster (fsid: $CEPH_CLUSTER_FSID)"
  "$SCRIPT_DIR"/parallel-cephadm "${param_hosts[@]}" \
    rm-cluster \
    --force \
    --fsid "$CEPH_CLUSTER_FSID"
}


main() {
  deploy_ceph
  tear_down_ceph
}
main
