#!/usr/bin/env bash

set -euo pipefail

readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$SCRIPT_DIR"

readonly CEPH_FSID="$(grep -oP 'fsid = \K.+' deployment_data_root/etc/ceph/ceph.conf)"

./parallel-cephadm shell \
  --keyring deployment_data_root/etc/ceph/ceph.client.admin.keyring \
  --config deployment_data_root/etc/ceph/ceph.conf --fsid "$CEPH_FSID" -- "$@"
