#!/usr/bin/env bash
#
# Require bash version >= 4.4
#
# This script depends on passwordless ssh and passwordless sudo via the current
# user ($USER) on remote hosts.

set -euo pipefail

readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# shellcheck source=./common.sh
. "$SCRIPT_DIR/common.sh"


usage() {
  cat <<EOF
Usage: $0 [OPTIONS] CEPHADM_ARGS

Options:
  --hosts HOST_FILE, --hosts=HOST_FILE
                             hosts file (each line "[user@]host[:port]")
  --host HOST_STRING, --host=HOST_STRING
                             additional host entries ("[user@]host[:port]")

Running the script without specifying hosts will only perform local execution.
EOF
}

if (( $# == 0 )); then
  usage
  exit
fi

HOST_PARAMS=()
CEPHADM_PARAMS=()
# loop positional params: https://unix.stackexchange.com/a/314041
for (( idx = 1; idx <= $#; idx++ )); do
  if [[ "${!idx}" == @(--hosts|--host) ]]; then
    HOST_PARAMS+=("${!idx}")
    (( idx++ ))
    if [[ -z "${!idx:-}" ]]; then
      usage
      common::err $(( ERR_STATUS_START + 1 )) "Missing parameter for '${HOST_PARAMS[-1]}'"
    fi
    HOST_PARAMS+=("${!idx}")
    continue
  fi

  if [[ "${!idx}" =~ ^(--hosts=|--host=) ]]; then
    HOST_PARAMS+=("${!idx}")
    continue
  fi

  CEPHADM_PARAMS+=("${!idx}")
done
common::debug HOST_PARAMS: "$(common::print_array HOST_PARAMS)"
common::debug CEPHADM_PARAMS: "$(common::print_array CEPHADM_PARAMS)"

if (( "${#HOST_PARAMS[@]}" )); then
  common::check_if_parallel_ssh_installed
fi

readonly DEFAULT_BIN_DIR="$PWD"/cephadm_target/bin
: "${CEPHADM:="$DEFAULT_BIN_DIR"/cephadm}"
if ! [[ -x "$CEPHADM" ]]; then
  common::debug "download cephadm"
  trace_on
  (
    mkdir -p "$DEFAULT_BIN_DIR" \
      && cd "$DEFAULT_BIN_DIR" \
      && curl --silent --remote-name --location https://github.com/ceph/ceph/raw/octopus/src/cephadm/cephadm \
      && chmod +x cephadm
  )
  trace_off
fi

if (( "${#HOST_PARAMS[@]}" )); then
  trace_on
  parallel-ssh \
    "${PARALLEL_SSH_OPTIONS[@]}" \
    "${HOST_PARAMS[@]}" \
    "sudo python3 -u - ${CEPHADM_PARAMS[*]}" < "${CEPHADM}"
  trace_off
else
  trace_on
  sudo "$CEPHADM" "${CEPHADM_PARAMS[@]}"
  trace_off
fi
