#!/usr/bin/env bash
#
# Require bash version >= 4.4
#
# This script depends on passwordless ssh to remote hosts.

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
readonly SCRIPT_DIR
# shellcheck source=./common.sh
. "$SCRIPT_DIR/common.sh"

if ! common::is_program_installed "parallel-ssh"; then
  common::err $(( ERR_STATUS_START + 1 )) "Please install parallel-ssh"
fi

# Test whether stdin has input using [ -t 0 ]
#   https://stackoverflow.com/a/2456870/2926646
#   https://unix.stackexchange.com/a/15683
if [[ -t 0 ]]; then
  common::debug "command from cmdline"
else
  common::debug "command from stdin"
  _SEND_INPUT="--send-input"
fi

trace_on
parallel-ssh \
  --par "${PARALLEL_SSH_THREADS:-5}" \
  --timeout 0 \
  --extra-args "${SSH_COMM_OPTIONS[*]}" \
  --inline \
  ${_SEND_INPUT:-} \
  --print "$@"
trace_off
