#!/usr/bin/env bash
#
# Require bash version >= 4.4
#
# This script depends on passwordless ssh and passwordless sudo via the current
# user ($USER) on remote hosts.

set -euo pipefail

readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# shellcheck source=./common.sh
. "$SCRIPT_DIR/common.sh"

if ! common::is_program_installed "parallel-ssh"; then
  common::err $(( ERR_STATUS_START + 1 )) "Please install parallel-ssh"
fi

trace_on
parallel-ssh \
  --par "${PARALLEL_SSH_THREADS:-5}" \
  --timeout 0 \
  --extra-args "${SSH_COMM_OPTIONS[*]}" \
  --inline \
  --send-input \
  --print "$@"
trace_off
