#!/usr/bin/env bash
#
# Require bash version >= 4.4
#
# This script depends on passwordless ssh and passwordless sudo via
# the current user ($USER) on remote hosts.

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
readonly SCRIPT_DIR
CMD_MODE=false "$SCRIPT_DIR"/parallel-exec-script \
  -e EFFECTIVE_USER="${EFFECTIVE_USER:-$USER}" --script=install/docker "$@"
